#!/bin/sh

WORDSET=$1
DICT=$2

echo "#" looking up $(basename $WORDSET) in $(basename $DICT)

echo 'Generated by `' $0 $@ '`'.

while read -r line; do
    echo
    echo "## $line"
    echo
    for word in $line; do
        grep -i "^$word[([:space:]]" $DICT | while read -r result; do
            echo "    $result"
        done
    done
done < $WORDSET
